/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTheFurlongRacingTrackerRouteImport } from './routes/dashboard/the-furlong/racing-tracker'
import { Route as DashboardTheFurlongPlannerRouteImport } from './routes/dashboard/the-furlong/planner'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTheFurlongRacingTrackerRoute =
  DashboardTheFurlongRacingTrackerRouteImport.update({
    id: '/the-furlong/racing-tracker',
    path: '/the-furlong/racing-tracker',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTheFurlongPlannerRoute =
  DashboardTheFurlongPlannerRouteImport.update({
    id: '/the-furlong/planner',
    path: '/the-furlong/planner',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/the-furlong/planner': typeof DashboardTheFurlongPlannerRoute
  '/dashboard/the-furlong/racing-tracker': typeof DashboardTheFurlongRacingTrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/the-furlong/planner': typeof DashboardTheFurlongPlannerRoute
  '/dashboard/the-furlong/racing-tracker': typeof DashboardTheFurlongRacingTrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/the-furlong/planner': typeof DashboardTheFurlongPlannerRoute
  '/dashboard/the-furlong/racing-tracker': typeof DashboardTheFurlongRacingTrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/the-furlong/planner'
    | '/dashboard/the-furlong/racing-tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/the-furlong/planner'
    | '/dashboard/the-furlong/racing-tracker'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/the-furlong/planner'
    | '/dashboard/the-furlong/racing-tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/the-furlong/racing-tracker': {
      id: '/dashboard/the-furlong/racing-tracker'
      path: '/the-furlong/racing-tracker'
      fullPath: '/dashboard/the-furlong/racing-tracker'
      preLoaderRoute: typeof DashboardTheFurlongRacingTrackerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/the-furlong/planner': {
      id: '/dashboard/the-furlong/planner'
      path: '/the-furlong/planner'
      fullPath: '/dashboard/the-furlong/planner'
      preLoaderRoute: typeof DashboardTheFurlongPlannerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTheFurlongPlannerRoute: typeof DashboardTheFurlongPlannerRoute
  DashboardTheFurlongRacingTrackerRoute: typeof DashboardTheFurlongRacingTrackerRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTheFurlongPlannerRoute: DashboardTheFurlongPlannerRoute,
  DashboardTheFurlongRacingTrackerRoute: DashboardTheFurlongRacingTrackerRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
